### ISSUE TITLE
Promtail not compiled with systemd journal support

### ISSUE THREAD

**Issue by dbruno74** [canonical/grafana-agent-snap#34]
The grafana agent v0.36.1 is not supporting systemd journal as per the following warning:
```
Sep 13 13:57:28 ubuntu grafana-agent.grafana-agent[844875]: ts=2023-09-13T13:57:28.286907345Z caller=journaltargetmanager.go:29 level=warn component=logs logs_config=default msg="WARNING!!! Journal target was configured but support for reading the systemd journal is not compiled into this build of promtail!"
```

To reproduce:
- snap install grafana-agent
- configure $SNAP_DATA/etc/grafana-agent-yaml to include journal scraping, e.g.
```
    scrape_configs:
      - job_name: journal
        journal:
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
```
- snap restart grafana-agent
